/** @type {import('tailwindcss').Config} */
// Tokens transcribed verbatim from the approved Stitch export
// (stitch_prime_estates_website_ui_ux -> DESIGN.md + code.html tailwind.config)
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container-low': '#f4f3f1',
        'on-surface-variant': '#45464c',
        'on-tertiary-fixed-variant': '#005323',
        'on-error-container': '#93000a',
        'on-surface': '#1a1c1a',
        'on-primary-container': '#7d8497',
        'surface-container-high': '#e9e8e5',
        'error-container': '#ffdad6',
        'on-primary': '#ffffff',
        'surface-bright': '#faf9f6',
        'primary-fixed': '#dce2f7',
        'on-background': '#1a1c1a',
        background: '#faf9f6',
        'on-secondary': '#ffffff',
        'inverse-primary': '#c0c6db',
        'on-secondary-container': '#682c00',
        'tertiary-fixed-dim': '#79db8d',
        'outline-variant': '#c6c6cd',
        'secondary-fixed': '#ffdbca',
        'surface-tint': '#575e70',
        'on-tertiary-fixed': '#00210a',
        'primary-container': '#141b2b',
        tertiary: '#000000',
        surface: '#faf9f6',
        'on-primary-fixed': '#141b2b',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#339650',
        'on-error': '#ffffff',
        'primary-fixed-dim': '#c0c6db',
        'surface-container': '#efeeeb',
        'surface-container-lowest': '#ffffff',
        primary: '#000000',
        'tertiary-container': '#00210a',
        error: '#ba1a1a',
        'on-secondary-fixed': '#331200',
        'tertiary-fixed': '#95f8a7',
        'inverse-surface': '#2f312f',
        outline: '#76777d',
        'secondary-container': '#fd8a42',
        'inverse-on-surface': '#f2f1ee',
        'surface-dim': '#dbdad7',
        'secondary-fixed-dim': '#ffb68e',
        'surface-container-highest': '#e3e2e0',
        'surface-variant': '#e3e2e0',
        'on-primary-fixed-variant': '#404758',
        'on-secondary-fixed-variant': '#763300',
        secondary: '#9b4500',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        gutter: '1.5rem',
        'space-sm': '0.5rem',
        'gutter-desktop': '2rem',
        'margin-mobile': '1rem',
        'margin-desktop': '4rem',
        'space-xs': '0.25rem',
        'gutter-mobile': '1rem',
        'space-md': '1rem',
        'space-xl': '2.5rem',
        'space-lg': '1.5rem',
        margin: '1.5rem',
      },
      fontFamily: {
        'body-sm': ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        'label-ui': ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        'body-lg': ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        'metric-price': ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        'body-md': ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        'headline-lg-mobile': ['"Playfair Display"', 'Georgia', 'serif'],
        'display-hero': ['"Playfair Display"', 'Georgia', 'serif'],
        'headline-sm': ['"Playfair Display"', 'Georgia', 'serif'],
        'title-md': ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        'title-lg': ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        'display-hero-mobile': ['"Playfair Display"', 'Georgia', 'serif'],
        'headline-lg': ['"Playfair Display"', 'Georgia', 'serif'],
        'headline-md': ['"Playfair Display"', 'Georgia', 'serif'],
        'label-caps': ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'body-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
        'label-ui': ['13px', { lineHeight: '18px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '26px', fontWeight: '400' }],
        'metric-price': ['24px', { lineHeight: '30px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', letterSpacing: '0em', fontWeight: '600' }],
        'display-hero': ['56px', { lineHeight: '64px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-sm': ['22px', { lineHeight: '28px', fontWeight: '500' }],
        'title-md': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'title-lg': ['18px', { lineHeight: '26px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'display-hero-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-md': ['28px', { lineHeight: '36px', fontWeight: '500' }],
        'label-caps': ['11px', { lineHeight: '16px', letterSpacing: '0.08em', fontWeight: '700' }],
      },
      boxShadow: {
        // Elevation scale from DESIGN.md "Elevation & Depth"
        lvl1: '0 1px 3px rgba(17,24,39,0.04), 0 6px 16px -4px rgba(17,24,39,0.03)',
        lvl2: '0 12px 32px -6px rgba(17,24,39,0.08), 0 4px 12px -2px rgba(17,24,39,0.03)',
        lvl3: '0 24px 48px -12px rgba(17,24,39,0.16)',
        float: '0 20px 50px rgba(20,27,43,0.12)',
      },
      maxWidth: { shell: '1440px' },
      keyframes: {
        'fade-up': { '0%': { opacity: '0', transform: 'translateY(18px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        'fade-in': { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        shimmer: { '100%': { transform: 'translateX(100%)' } },
      },
      animation: {
        'fade-up': 'fade-up .7s cubic-bezier(.16,1,.3,1) both',
        'fade-in': 'fade-in .5s ease both',
      },
    },
  },
  plugins: [],
};
