/**
 * Self-hosts the fonts as VARIABLE fonts, latin subset only.
 *
 * Why variable: the design uses Plus Jakarta Sans at 400/500/600/700 and
 * Playfair Display at 500/600 plus a 400 italic. As static files that is six
 * separate downloads (~146 KB). A variable font covers the whole weight axis
 * in one file, so the browser makes one request per family instead of four.
 *
 * Why self-host: fonts.googleapis.com costs a DNS + TLS handshake to a third
 * party plus a render-blocking stylesheet. Local files are served from our own
 * CDN with an immutable cache header.
 *
 * Only the `latin` subset is kept — no Cyrillic/Greek/Vietnamese.
 */
import fs from 'node:fs/promises';

const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36';

const SPECS = [
  { css: 'Plus+Jakarta+Sans:wght@400..700',              file: 'jakarta-var',     family: 'Plus Jakarta Sans', style: 'normal', weight: '400 700' },
  { css: 'Playfair+Display:wght@500..700',               file: 'playfair-var',    family: 'Playfair Display',  style: 'normal', weight: '500 700' },
  { css: 'Playfair+Display:ital,wght@1,400..600',        file: 'playfair-var-i',  family: 'Playfair Display',  style: 'italic', weight: '400 600' },
];

const UNICODE_RANGE =
  'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,' +
  'U+2000-206F,U+20AC,U+20B9,U+2122,U+2190-2193,U+2212,U+2215,U+FEFF,U+FFFD';

let css = '/* AUTO-GENERATED by .qa/fetch-fonts.mjs — do not edit. */\n';
let total = 0;

for (const spec of SPECS) {
  const url = `https://fonts.googleapis.com/css2?family=${spec.css}&display=swap`;
  const text = await (await fetch(url, { headers: { 'User-Agent': UA } })).text();

  // Grab the `latin` block (the comment label precedes each @font-face).
  let woff2 = null;
  for (const raw of text.split('/*').slice(1)) {
    const label = raw.slice(0, raw.indexOf('*/')).trim();
    if (label !== 'latin') continue;
    const m = /src:\s*url\((https:[^)]+\.woff2)\)/.exec(raw);
    if (m) { woff2 = m[1]; break; }
  }
  if (!woff2) { console.error(`  !! no latin block for ${spec.css}`); continue; }

  const buf = Buffer.from(await (await fetch(woff2, { headers: { 'User-Agent': UA } })).arrayBuffer());
  await fs.writeFile(`public/fonts/${spec.file}.woff2`, buf);
  total += buf.length;

  css += `@font-face{font-family:'${spec.family}';font-style:${spec.style};`
       + `font-weight:${spec.weight};font-display:swap;`
       + `src:url('/fonts/${spec.file}.woff2') format('woff2-variations');`
       + `unicode-range:${UNICODE_RANGE};}\n`;

  console.log(`  ${(spec.file + '.woff2').padEnd(22)} ${(buf.length / 1024).toFixed(1)} KB  (${spec.family} ${spec.style} ${spec.weight})`);
}

await fs.writeFile('public/fonts/fonts.css', css);
console.log(`\ntotal ${(total / 1024).toFixed(1)} KB across ${SPECS.length} files`);
