import React, { useEffect, useRef, useState } from 'react';
import { useEscape, useScrollLock } from '../hooks';
import { ICON_PATHS } from './icon-paths';

/* ------------------------------- icon ------------------------------- */

/**
 * Inline SVG icon.
 *
 * This used to render a <span> styled by the Material Symbols icon *font*.
 * That font is a 3.9 MB variable font — for the 60 glyphs this app actually
 * uses. It was also render-blocking (a stylesheet in <head>) and caused a
 * flash of unstyled ligature text before it loaded.
 *
 * The same glyphs are now inlined as path data (~17 KB of source, heavily
 * compressed in the bundle and tree-shaken to what is imported). No network
 * request, no FOUT, no layout shift.
 *
 * The prop signature is unchanged, so every existing call site still works.
 * `currentColor` keeps icons inheriting text colour exactly as the font did.
 */
export const Icon = React.memo(function Icon({
  name, size = 20, className = '', fill = false,
}: { name: string; size?: number; className?: string; fill?: boolean }) {
  const d = ICON_PATHS[name];
  if (!d) {
    if (import.meta.env.DEV) console.warn(`[Icon] unknown icon "${name}" — add it to .qa/gen-icons.mjs`);
    return <span style={{ width: size, height: size, display: 'inline-block' }} aria-hidden="true" />;
  }
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 -960 960 960"
      width={size}
      height={size}
      fill="currentColor"
      className={`inline-block shrink-0 select-none align-middle ${className}`}
      style={fill ? { fillOpacity: 1 } : undefined}
      aria-hidden="true"
      focusable="false"
    >
      <path d={d} />
    </svg>
  );
});

/* --------------------------- lazy image ----------------------------- */

/**
 * Image with skeleton placeholder, native lazy loading, async decoding and a
 * graceful fallback. Alt text is required by the type signature.
 */
/**
 * Responsive, lazy image.
 *
 * For images that ship with the app (/media/*) a build step generates AVIF +
 * WebP derivatives at 400/800/1408px (see .qa/gen-images.mjs). This emits a
 * <picture> so the browser downloads the smallest file that suits its
 * viewport and DPR: a property card on a phone pulls ~12 KB instead of the
 * ~266 KB original.
 *
 * For uploaded images (Supabase Storage) it asks the CDN to render the right
 * width via render/image transform params, and otherwise falls back to the
 * original URL untouched.
 *
 * `width`/`height` are always emitted when known so the browser reserves the
 * box before the bytes arrive — this is what keeps CLS at zero.
 */

// Widths generated by .qa/gen-images.mjs
const IMG_WIDTHS = [400, 800, 1408];

/** Bundled /media images have pre-generated derivatives in /media/r. */
function localDerivatives(src: string) {
  const m = /^\/media\/([^/]+)\.(jpe?g|png)$/i.exec(src);
  if (!m) return null;
  const base = m[1];
  const set = (ext: string) =>
    IMG_WIDTHS.map((w) => `/media/r/${base}-${w}.${ext} ${w}w`).join(', ');
  return {
    avif: set('avif'),
    webp: set('webp'),
    jpg: set('jpg'),
    fallback: `/media/r/${base}-800.jpg`,
  };
}

/**
 * Supabase Storage can resize on the fly. Public object URLs look like
 *   /storage/v1/object/public/<bucket>/<key>
 * and the transforming endpoint is
 *   /storage/v1/render/image/public/<bucket>/<key>?width=...
 *
 * IMPORTANT: image transformation is a PAID Supabase feature. On the free
 * plan the render endpoint returns an error, which would break every
 * uploaded photo. So this is opt-in: set VITE_SUPABASE_IMAGE_TRANSFORMS=true
 * only on a plan that includes it. When off, uploaded images are served as
 * the original object (still lazy-loaded, still correctly sized by CSS).
 *
 * This flag is a plain boolean, not a credential — nothing secret is exposed
 * by compiling it into the bundle.
 */
const SUPABASE_TRANSFORMS = import.meta.env.VITE_SUPABASE_IMAGE_TRANSFORMS === 'true';

function supabaseDerivatives(src: string) {
  if (!SUPABASE_TRANSFORMS) return null;
  if (!src.includes('/storage/v1/object/public/')) return null;
  const render = src.replace('/storage/v1/object/public/', '/storage/v1/render/image/public/');
  const at = (w: number) => `${render}?width=${w}&quality=75`;
  return {
    avif: null,
    webp: null,
    jpg: IMG_WIDTHS.map((w) => `${at(w)} ${w}w`).join(', '),
    fallback: at(800),
  };
}

export function Img({
  src, alt, className = '', imgClassName = '', priority = false, sizes,
  width, height,
}: {
  src: string; alt: string; className?: string; imgClassName?: string;
  priority?: boolean; sizes?: string; width?: number; height?: number;
}) {
  const [loaded, setLoaded] = useState(false);
  const [failed, setFailed] = useState(false);
  const imgRef = useRef<HTMLImageElement>(null);

  // A cached image can finish decoding before React attaches onLoad, which
  // would leave it stuck at opacity-0 behind the skeleton. Catch that here.
  useEffect(() => {
    const el = imgRef.current;
    const done = !!el?.complete;
    setFailed(done && el!.naturalWidth === 0);
    setLoaded(done && el!.naturalWidth > 0);
  }, [src]);

  const d = localDerivatives(src) ?? supabaseDerivatives(src);
  // Default: card-sized on phones, roughly a third of the shell on desktop.
  const sizeAttr = sizes ?? '(max-width: 767px) 100vw, (max-width: 1279px) 50vw, 33vw';

  const img = (
    <img
      ref={imgRef}
      src={d ? d.fallback : src}
      srcSet={d && !d.avif && !d.webp ? d.jpg : undefined}
      sizes={d ? sizeAttr : undefined}
      alt={alt}
      width={width}
      height={height}
      loading={priority ? 'eager' : 'lazy'}
      decoding={priority ? 'sync' : 'async'}
      // lowercase attribute: React 18 does not map the camelCase prop
      {...{ fetchpriority: priority ? 'high' : 'auto' }}
      onLoad={() => setLoaded(true)}
      onError={() => setFailed(true)}
      className={`w-full h-full object-cover transition-opacity duration-500 ${loaded ? 'opacity-100' : 'opacity-0'} ${imgClassName}`}
    />
  );

  return (
    <div className={`relative overflow-hidden bg-surface-container ${className}`}>
      {!loaded && !failed && <div className="absolute inset-0 skeleton" aria-hidden="true" />}
      {failed ? (
        <div className="absolute inset-0 grid place-items-center bg-surface-container text-outline">
          <Icon name="imagesmode" size={28} />
        </div>
      ) : d && (d.avif || d.webp) ? (
        <picture>
          {d.avif && <source type="image/avif" srcSet={d.avif} sizes={sizeAttr} />}
          {d.webp && <source type="image/webp" srcSet={d.webp} sizes={sizeAttr} />}
          {img}
        </picture>
      ) : (
        img
      )}
    </div>
  );
}

/* ------------------------------- modal ------------------------------ */

export function Modal({
  open, onClose, title, children, footer, size = 'md',
}: {
  open: boolean; onClose: () => void; title: string;
  children: React.ReactNode; footer?: React.ReactNode; size?: 'sm' | 'md' | 'lg';
}) {
  const panelRef = useRef<HTMLDivElement>(null);
  useScrollLock(open);
  useEscape(open, onClose);

  useEffect(() => {
    if (!open) return;
    const timer = setTimeout(() => {
      const focusable = panelRef.current?.querySelector<HTMLElement>(
        'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])',
      );
      focusable?.focus();
    }, 30);
    return () => clearTimeout(timer);
  }, [open]);

  // Focus trap so keyboard users can't tab behind the scrim.
  useEffect(() => {
    if (!open) return;
    const handler = (e: KeyboardEvent) => {
      if (e.key !== 'Tab' || !panelRef.current) return;
      const items = Array.from(
        panelRef.current.querySelectorAll<HTMLElement>(
          'button:not([disabled]), [href], input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])',
        ),
      ).filter((el) => el.offsetParent !== null);
      if (!items.length) return;
      const first = items[0];
      const last = items[items.length - 1];
      if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last.focus(); }
      else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first.focus(); }
    };
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, [open]);

  if (!open) return null;
  const width = size === 'sm' ? 'max-w-md' : size === 'lg' ? 'max-w-3xl' : 'max-w-xl';

  return (
    <div className="fixed inset-0 z-[90] flex items-end sm:items-center justify-center p-0 sm:p-4">
      <div
        className="absolute inset-0 bg-[rgba(17,24,39,0.45)] backdrop-blur-[8px] animate-fade-in"
        onClick={onClose}
        aria-hidden="true"
      />
      <div
        ref={panelRef}
        role="dialog"
        aria-modal="true"
        aria-label={title}
        className={`relative w-full ${width} bg-surface-container-lowest rounded-t-2xl sm:rounded-2xl shadow-lvl3
                    max-h-[92vh] sm:max-h-[85vh] flex flex-col animate-fade-up`}
      >
        <header className="flex items-center justify-between gap-4 px-space-lg py-space-md border-b border-[#e7e5e4] shrink-0">
          <h2 className="font-headline-sm text-headline-sm text-on-surface pr-2">{title}</h2>
          <button
            onClick={onClose}
            className="w-9 h-9 grid place-items-center rounded-full hover:bg-surface-container text-on-surface-variant shrink-0"
            aria-label="Close dialog"
          >
            <Icon name="close" size={20} />
          </button>
        </header>
        <div className="px-space-lg py-space-md overflow-y-auto flex-1">{children}</div>
        {footer && (
          <footer className="px-space-lg py-space-md border-t border-[#e7e5e4] shrink-0 bg-surface-container-low rounded-b-2xl">
            {footer}
          </footer>
        )}
      </div>
    </div>
  );
}

/* --------------------------- confirm dialog -------------------------- */

export function ConfirmDialog({
  open, title, message, confirmLabel = 'Confirm', tone = 'danger', busy = false, onConfirm, onCancel,
}: {
  open: boolean; title: string; message: string; confirmLabel?: string;
  tone?: 'danger' | 'primary'; busy?: boolean; onConfirm: () => void; onCancel: () => void;
}) {
  return (
    <Modal
      open={open}
      onClose={onCancel}
      title={title}
      size="sm"
      footer={
        <div className="flex flex-col-reverse sm:flex-row sm:justify-end gap-2">
          <button className="btn-secondary btn-sm" onClick={onCancel} disabled={busy}>Cancel</button>
          <button
            className={`btn btn-sm px-space-lg py-2.5 text-on-primary ${tone === 'danger' ? 'bg-error hover:bg-[#93000a]' : 'bg-primary-container hover:bg-[#2a3550]'}`}
            onClick={onConfirm}
            disabled={busy}
          >
            {busy && <Spinner size={14} />}
            {busy ? 'Working…' : confirmLabel}
          </button>
        </div>
      }
    >
      <p className="font-body-md text-body-md text-on-surface-variant">{message}</p>
    </Modal>
  );
}

/* ------------------------------ spinner ------------------------------ */

export function Spinner({ size = 18, className = '' }: { size?: number; className?: string }) {
  return (
    <svg
      className={`animate-spin ${className}`}
      style={{ width: size, height: size }}
      viewBox="0 0 24 24"
      fill="none"
      aria-hidden="true"
    >
      <circle cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="3" className="opacity-25" />
      <path d="M22 12a10 10 0 0 1-10 10" stroke="currentColor" strokeWidth="3" strokeLinecap="round" />
    </svg>
  );
}

/* ------------------------------- states ------------------------------ */

export function EmptyState({
  icon = 'search_off', title, message, action,
}: { icon?: string; title: string; message: string; action?: React.ReactNode }) {
  return (
    <div className="text-center py-16 px-6">
      <div className="w-14 h-14 mx-auto rounded-full bg-surface-container grid place-items-center text-on-surface-variant mb-4">
        <Icon name={icon} size={26} />
      </div>
      <h3 className="font-headline-sm text-headline-sm text-on-surface mb-1.5">{title}</h3>
      <p className="font-body-md text-body-md text-on-surface-variant max-w-md mx-auto mb-5">{message}</p>
      {action}
    </div>
  );
}

export function ErrorState({ message, onRetry }: { message: string; onRetry?: () => void }) {
  return (
    <div className="text-center py-16 px-6">
      <div className="w-14 h-14 mx-auto rounded-full bg-error-container grid place-items-center text-on-error-container mb-4">
        <Icon name="error" size={26} />
      </div>
      <h3 className="font-headline-sm text-headline-sm text-on-surface mb-1.5">Something went wrong</h3>
      <p className="font-body-md text-body-md text-on-surface-variant max-w-md mx-auto mb-5">{message}</p>
      {onRetry && <button className="btn-secondary btn-sm" onClick={onRetry}>Try again</button>}
    </div>
  );
}

/* ---------------------------- form helpers --------------------------- */

export function Field({
  label, htmlFor, error, hint, required, children, className = '',
}: {
  label: string; htmlFor?: string; error?: string; hint?: string;
  required?: boolean; children: React.ReactNode; className?: string;
}) {
  return (
    <div className={className}>
      <label className="label" htmlFor={htmlFor}>
        {label}
        {required && <span className="text-error ml-0.5" aria-hidden="true"> *</span>}
      </label>
      {children}
      {hint && !error && <p className="mt-1 font-body-sm text-body-sm text-on-surface-variant">{hint}</p>}
      {error && (
        <p className="mt-1 font-body-sm text-body-sm text-error flex items-center gap-1" role="alert">
          <Icon name="error" size={14} />
          {error}
        </p>
      )}
    </div>
  );
}

export function Toggle({
  checked, onChange, label, id,
}: { checked: boolean; onChange: (v: boolean) => void; label: string; id: string }) {
  return (
    <label htmlFor={id} className="flex items-center gap-3 cursor-pointer group">
      <span className="relative inline-block shrink-0">
        <input
          id={id}
          type="checkbox"
          className="sr-only peer"
          checked={checked}
          onChange={(e) => onChange(e.target.checked)}
        />
        <span
          className="block w-11 h-6 rounded-full bg-surface-container-highest transition-colors
                     peer-checked:bg-on-tertiary-fixed-variant peer-focus-visible:ring-2 peer-focus-visible:ring-secondary peer-focus-visible:ring-offset-2"
        />
        <span
          className={`absolute top-0.5 left-0.5 w-5 h-5 rounded-full bg-white shadow transition-transform
                      ${checked ? 'translate-x-5' : ''}`}
        />
      </span>
      <span className="font-body-md text-body-md text-on-surface select-none">{label}</span>
    </label>
  );
}

/* ----------------------------- map embed ---------------------------- */

/**
 * Click-to-load Google Maps embed.
 *
 * A Google Maps iframe pulls roughly 1.6 MB of third-party JavaScript across
 * ~10 requests, and `loading="lazy"` does not help when the map sits inside
 * the first viewport on a phone — which it does on both the property detail
 * and contact pages. It was also the largest source of layout shift.
 *
 * This renders a lightweight, styled placeholder with the location name and
 * only mounts the real iframe once the visitor asks for it. Anyone who just
 * wants the phone number never pays for the map. A plain link to Google Maps
 * is always present, so the information is reachable without the embed and
 * remains available to crawlers and keyboard users.
 */
export function MapEmbed({
  src, title, label, className = '',
}: { src: string; title: string; label?: string; className?: string }) {
  const [active, setActive] = useState(false);

  if (active) {
    return (
      <iframe
        title={title}
        src={src}
        className={`w-full h-full border-0 ${className}`}
        loading="lazy"
        referrerPolicy="no-referrer-when-downgrade"
        allowFullScreen
      />
    );
  }

  return (
    <button
      type="button"
      onClick={() => setActive(true)}
      className={`group relative w-full h-full flex flex-col items-center justify-center gap-space-xs
                  bg-surface-container hover:bg-surface-container-high transition-colors
                  focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary ${className}`}
      aria-label={`${title} — load interactive map`}
    >
      {/* Decorative grid suggesting a map, drawn in CSS (no network cost). */}
      <span
        aria-hidden="true"
        className="absolute inset-0 opacity-[0.18]
                   bg-[linear-gradient(to_right,currentColor_1px,transparent_1px),linear-gradient(to_bottom,currentColor_1px,transparent_1px)]
                   bg-[size:2rem_2rem] text-outline"
      />
      <span className="relative flex items-center gap-space-xs rounded-full bg-surface-container-lowest px-4 py-2 shadow-lvl1
                       group-hover:shadow-lvl2 transition-shadow">
        <Icon name="pin_drop" size={18} className="text-secondary" />
        <span className="font-label-ui text-label-ui text-on-surface">Load map</span>
      </span>
      {label && (
        <span className="relative font-body-sm text-body-sm text-on-surface-variant px-4 text-center">
          {label}
        </span>
      )}
    </button>
  );
}
